spring:
  application:
    name: eureka-server
server:
  port: 8070
eureka:
  instance:
    hostname: eurekaserver
  client:
#    tell the config server to not register wwith the Eureka Server
    registerWithEureka: false
#    to not cache registery information locally
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
#    sets the time to wait before the server takes requests.
#    if we don't set this attribute, by default Eureka will wait for 5 mins before advertising other services.
    waitTimeInMsWhenSyncEmpty: 5

